esphome:
  name: bbq-monitor

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
# SPI-Bus (SSD1322)
spi:
  - id: spi1
    clk_pin: GPIO12
    mosi_pin: GPIO11
    miso_pin: GPIO13
    interface: spi2
    
sensor:
  # Akku
  - platform: adc
    pin: GPIO2
    id: battery_voltage_raw
    update_interval: 5s
    attenuation: 12db
    filters:
      - multiply: 2.0
    unit_of_measurement: V

  # BBQ Sensor 1
  - platform: ntc
    sensor: resistance_sensor1
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "BBQ Temperatur 1"
    id: bbq_temp1

  - platform: resistance
    id: resistance_sensor1
    sensor: adc_sensor1
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: adc_sensor1
    pin: GPIO5
    attenuation: 12db

  # BBQ Sensor 2
  - platform: ntc
    sensor: resistance_sensor2
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "BBQ Temperatur 2"
    id: bbq_temp2

  - platform: resistance
    id: resistance_sensor2
    sensor: adc_sensor2
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: adc_sensor2
    pin: GPIO6
    attenuation: 12db

  # BBQ Sensor 3
  - platform: ntc
    sensor: resistance_sensor3
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "BBQ Temperatur 3"
    id: bbq_temp3

  - platform: resistance
    id: resistance_sensor3
    sensor: adc_sensor3
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: adc_sensor3
    pin: GPIO7
    attenuation: 12db

  # BBQ Sensor 4
  - platform: ntc
    sensor: resistance_sensor4
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "BBQ Temperatur 4"
    id: bbq_temp4

  - platform: resistance
    id: resistance_sensor4
    sensor: adc_sensor4
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: adc_sensor4
    pin: GPIO8
    attenuation: 12db

  # BBQ Sensor 5
  - platform: ntc
    sensor: resistance_sensor5
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "BBQ Temperatur 5"
    id: bbq_temp5

  - platform: resistance
    id: resistance_sensor5
    sensor: adc_sensor5
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    id: adc_sensor5
    pin: GPIO9
    attenuation: 12db
    
# Input Number für eigene Wunschtemperaturen
number:
  - platform: template
    name: "BBQ Wunschtemperatur 1"
    id: bbq_target1
    min_value: 20
    max_value: 99
    step: 1
    optimistic: true
    initial_value: 57   # Medium

  - platform: template
    name: "BBQ Wunschtemperatur 2"
    id: bbq_target2
    min_value: 20
    max_value: 99
    step: 1
    optimistic: true
    initial_value: 57   # Medium

  - platform: template
    name: "BBQ Wunschtemperatur 3"
    id: bbq_target3
    min_value: 20
    max_value: 99
    step: 1
    optimistic: true
    initial_value: 57   # Medium

  - platform: template
    name: "BBQ Wunschtemperatur 4"
    id: bbq_target4
    min_value: 20
    max_value: 300
    step: 0.1
    optimistic: true
    initial_value: 57   # Medium

  - platform: template
    name: "BBQ Wunschtemperatur 5"
    id: bbq_target5
    min_value: 20
    max_value: 300
    step: 0.1
    optimistic: true
    initial_value: 57   # Medium

# Taster (GPIOs beliebig anpassen)
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Sensor wechseln"
    id: btn_next_sensor
    on_press:
      then:
        - lambda: |-
            id(active_sensor)++;
            if(id(active_sensor) > 5) id(active_sensor) = 1;
  - platform: status
    name: "Home Assistant Verbindung"
    id: ha_connected

  - platform: gpio
    pin:
      number: GPIO39
      mode: INPUT_PULLUP
      inverted: True
    name: "Garstufe wechseln"
    id: btn_change_stage
    on_press:
      then:
        - lambda: |-
            id(active_stage)++;
            if(id(active_stage) > 6) id(active_stage) = 1;


interval:
  - interval: 5s
    then:
      - lambda: |-
          // 8,4 V LiIon -> Prozent (0–100%)
          float v = id(battery_voltage_raw).state;
          int pct = (int)((v / 8.4) * 100.0);
          if(pct > 100) pct = 100;
          if(pct < 0) pct = 0;
          id(battery_percent) = pct;
    

# Globals für aktiven Sensor und Garstufe
globals:
  - id: active_sensor
    type: int
    restore_value: yes
    initial_value: '1'
  - id: active_stage
    type: int
    restore_value: yes
    initial_value: '1'
  - id: battery_percent
    type: int
    restore_value: no


# Fonts (Google Fonts)
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 12
  - file: "gfonts://Roboto"
    id: font_large
    size: 18
  - file: "gfonts://Roboto"
    id: font_stage
    size: 14

display:
  - platform: ssd1322_spi
    model: "SSD1322 256x64"
    spi_id: spi1
    cs_pin: GPIO16
    dc_pin: GPIO1
    reset_pin: GPIO15
    lambda: |-
      // --- Spalte 1: Geräteinfo ---
      it.printf(0, 0, id(font_small), "BBQ");
      it.printf(0, 12, id(font_small), "Thermometer");

      // Akkustand
      it.printf(0, 24, id(font_small), "Akku: %d%%", id(battery_percent));

      // --- Arrays für Sensoren ---
      float temps[5] = { id(bbq_temp1).state, id(bbq_temp2).state, id(bbq_temp3).state, id(bbq_temp4).state, id(bbq_temp5).state };
      float targets[5] = { id(bbq_target1).state, id(bbq_target2).state, id(bbq_target3).state, id(bbq_target4).state, id(bbq_target5).state };

      // Funktion für Soll-Garstufe
      auto get_stage = [](float target) -> const char* {
        if (target < 50) return "R";
        else if (target < 55) return "MR";
        else if (target < 60) return "M";
        else if (target < 65) return "MW";
        else if (target <= 100) return "WD";
        else return "E"; // Eigen
      };

      // --- Spalte 2: Sensor 1–3 ---
      int col2_x = 78;
      for(int i=0; i<3; i++){
        int y = 0 + i*18;
        it.printf(col2_x, y, id(font_small), "S%d %s %2.1f/%2.1f", i+1, get_stage(targets[i]), temps[i], targets[i]);
      }

      // --- Spalte 3: Sensor 4–5 ---
      int col3_x = 167;
      for(int i=3; i<5; i++){
        int y = 0 + (i-3)*18;
        it.printf(col3_x, y, id(font_small), "S%d %s %2.1f/%2.1f", i+1, get_stage(targets[i]), temps[i], targets[i]);
      }


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bratenthermometer"
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

captive_portal:
